services:

  mysql:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_URL}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pkea" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - spring.application.name=mysql
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=${DB_URL}
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 18

volumes:
  mysql_data: