name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev", "QA" ]
  pull_request:
    branches: [ "main", "dev", "QA" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:

      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11


      - name: Set up JDK 21
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'


      - name: Cache Maven packages
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build og test
      - name: Build with Maven (tests + package)
        run: mvn -B clean verify --file pom.xml


      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: test-results
          path: target/surefire-reports/


      - name: Add coverage to PR
        if: github.event_name == 'pull_request'
        id: jacoco
        uses: madrapps/jacoco-report@db37a3853dce197dbc9d47eb2d340e282944a738
        with:
          paths: |
            ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60